version: '3'
services:
  elsie-dee:
    image: "ekholabs/elsie-dee"
    container_name: "elsie-dee"
    ports:
      - "80:80"
    external_links:
      - configuration-service
      - eureka-service
    links:
      - elsie-deetect
      - elsie-deesight
      - elsie-dee-audiorip
      - elsie-dee-search
      - stream-services
    depends_on:
      - elsie-deetect
      - elsie-deesight
      - elsie-dee-audiorip
      - elsie-dee-search
      - stream-services
    networks:
      - elsie-dee-net
  elsie-deetect:
    image: "ekholabs/elsie-deetect"
    container_name: "elsie-deetect"
    ports:
      - "8080:8080"
    external_links:
      - configuration-service
      - eureka-service
    networks:
      - elsie-dee-net
  elsie-dee-search:
    image: "ekholabs/elsie-dee-search"
    container_name: "elsie-dee-search"
    ports:
      - "8087:8087"
    external_links:
      - configuration-service
      - eureka-service
    links:
      - elsie-dee-elastic
    depends_on:
      - elsie-dee-elastic
    networks:
      - elsie-dee-net
  elsie-dee-audiorip:
    image: "ekholabs/elsie-dee-audiorip"
    container_name: "elsie-dee-audiorip"
    ports:
      - "8086:8086"
    external_links:
      - configuration-service
      - eureka-service
    networks:
      - elsie-dee-net
  elsie-deesight:
    image: "ekholabs/elsie-deesight"
    container_name: "elsie-deesight"
    ports:
      - "8085:8085"
    external_links:
      - configuration-service
      - eureka-service
    links:
      - face-classifier
    depends_on:
      - face-classifier
    networks:
      - elsie-dee-net
  face-classifier:
    image: "ekholabs/face-classifier"
    container_name: "face-classifier"
    ports:
      - "8084:8084"
    networks:
      - elsie-dee-net
  stream-services:
    image: "ekholabs/stream-services"
    container_name: "stream-services"
    ports:
      - "8088:8088"
    networks:
      - elsie-dee-net
  elsie-dee-elastic:
    image: elasticsearch:2.4
    container_name: elsie-dee-elastic
    environment:
      - cluster.name=elastic-cluster
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elsie-dee-elastic/data
    ports:
      - 9200:9200
    networks:
      - elsie-dee-net

volumes:
  esdata1:
    driver: local

networks:
  elsie-dee-net:
    driver: overlay
